### ISSUE TITLE
Integration setup fails

### ISSUE THREAD

**Issue by cybis** [eifinger/here_travel_time_route_sensor#1]
The integration setup in `Home Assistant 2023.2.1` (running in a docker container) fails with an unexpected error:

![setup_error](https://user-images.githubusercontent.com/20976791/218334576-552cd021-1469-429e-8675-46fa4b36fc86.png)

The log contains the following exception:
```
Traceback (most recent call last):
  File "/config/custom_components/here_travel_time/config_flow.py", line 122, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/here_travel_time/config_flow.py", line 58, in validate_api_key
    RoutingApi(api_key).public_transport_timetable(
  File "/config/.local/lib/python3.10/site-packages/herepy/routing_api.py", line 241, in public_transport_timetable
    return self._route(waypoint_a, waypoint_b, modes, departure, arrival)
  File "/config/.local/lib/python3.10/site-packages/herepy/routing_api.py", line 67, in _route
    response = self.__get(self.URL_CALCULATE_ROUTE, data, RoutingResponse)
  File "/config/.local/lib/python3.10/site-packages/herepy/routing_api.py", line 40, in __get
    raise error_from_routing_service_error(json_data)
herepy.error.HEREError: Error occured on __get
```

**Comment by eifinger** [comment]
Thank you for opening this issue.
This is an intermittent error of the HERE API.

This repo needs to be updated to the new v8 api as in core and new functionality needs to be added to extract the route information.

**Comment by cybis** [comment]
Thanks a lot for the follow-up! Is an update planned for this repo?

**Comment by eifinger** [comment]
It's currently not very high on my todo list but I would gladly review and accept any contributions
